name: Deploy Vite App

on:
  push:
    branches:
      - main # Change this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm ci

      - name: Build the Vite app
        run: |
          npm run build

  deploy:
    needs: build # Wait for the 'build' job to finish before starting this job
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist # Change this to your build output directory
